<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<title></title>
	<link rel="stylesheet" href="">
	<style>
		body{font-size: 13px}
		table,div,p,ul{width: 300px;background-color: #eee;border: 1px solid #888;padding: 0px;margin: 10,0,10,0;}
	</style>
</head>
<body>
	<table>
		<tr>
			<td>Td1</td>
		</tr>
		<tr>
			<td>Td2</td>
		</tr>
	</table>
	<div>Div</div>
	<p>P</p>
	<div><span>Span</span></div>
	<ul>
		<li>Li1</li>
		<li>Li2</li>
	</ul>
</body>
</html>
